name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract version from package.json
        id: version
        run: |
          VERSION=$(jq -r '.version' ./angular-site/package.json)
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "MAJOR=$MAJOR" >> $GITHUB_ENV
          echo "MINOR=$MINOR" >> $GITHUB_ENV
          echo "MAJOR_MINOR=$MAJOR.$MINOR" >> $GITHUB_ENV
          echo "Extracted version: $VERSION (Major: $MAJOR, Minor: $MINOR)"

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./angular-site/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/earl-ceg3120:latest
            ${{ secrets.DOCKER_USERNAME }}/earl-ceg3120:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/earl-ceg3120:${{ env.MAJOR }}
            ${{ secrets.DOCKER_USERNAME }}/earl-ceg3120:${{ env.MAJOR_MINOR }}
